# Generated by Django 3.0.7 on 2020-09-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200917_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
