# Generated by Django 3.0.7 on 2020-09-19 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_auto_20200919_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(through='course.Score', to=settings.AUTH_USER_MODEL),
        ),
    ]
