# Generated by Django 3.0.7 on 2020-09-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acauth', '0002_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='/media/Avatar.jpg'),
        ),
    ]
