# Generated by Django 3.0.7 on 2020-09-14 08:04

import apps.acauth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200914_1559'),
        ('acauth', '0004_auto_20200914_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='superpower',
            field=models.ForeignKey(default=apps.acauth.models.get_superpower_default_id, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Superpower'),
        ),
    ]
