# Generated by Django 3.0.7 on 2020-09-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acauth', '0006_auto_20200914_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('del_director', '开除管理者')]},
        ),
    ]
