# Generated by Django 3.0.7 on 2020-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpower',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
