# Generated by Django 3.0.7 on 2020-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200911_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_level']},
        ),
        migrations.AlterModelOptions(
            name='schoollevel',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='school',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
