# Generated by Django 3.0.7 on 2020-10-03 08:20

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_todolist_todolisttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='data',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
