# Generated by Django 3.0.7 on 2020-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20201003_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
